source 'https://rubygems.org'

gem 'aws-sdk'
gem 'gems'
gem 'net-scp'
gem 'net-ssh'
gem 'pmap'
gem 'puma'
gem 'sequel'
gem 'sinatra'
gem 'sqlite3'

group :development do
	gem 'flamegraph'
	gem 'minitest'
	gem 'rack-mini-profiler'
	gem 'rerun'
	gem 'rubocop'
end
