source 'https://rubygems.org'

gem 'gems'
gem 'net-scp'
gem 'net-ssh'
gem 'pg'
gem 'pmap'
gem 'puma'
gem 'sequel'
gem 'sinatra'
gem 'vagrant_rbapi'

group :development do
	gem 'minitest'
	gem 'rack-test'
	gem 'rerun'
	gem 'rubocop'
end
