require_relative 'app'

task default: 'test'
task :test do
	Dir.glob('./test/test_*.rb') { |f| require f }
end

namespace :db do
	DB.loggers << Logger.new($stdout)

	task :migrate do
		Sequel.extension :migration
		Sequel::Migrator.run(DB, 'db/migrations')
	end

	task :update_packages do
		update_packages
	end

	task :update_ci do
		update_ci
	end

	task :clear_ci do
		clear_ci
	end
end

namespace :vm do
	provisioner = ENV['provisioner']
	provisioner = 'virtualbox' if provisioner.nil?

	task :run_ci_all do
		run_ci(:all, provisioner)
	end

	task :run_ci_daily do
		run_ci(:daily, provisioner)
	end

	num_of_packages = ENV['num_of_packages'].to_i
	task :run_ci_some do
		run_ci(num_of_packages, provisioner)
	end

	task :run_ci_untested do
		run_ci(:untested, provisioner)
	end
end
